# Generated by Django 4.1.2 on 2022-10-31 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='about',
            new_name='user',
        ),
    ]
